name: Compilar para Linux
on: [push, workflow_dispatch]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4
    
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar PyInstaller
        run: pip install pyinstaller
        
      - name: Crear Binario Linux
        run: |
          # Usamos comillas dobles para que el espacio antes del .py no rompa el comando
          pyinstaller --onefile --name "Sorteo_Linux" "Sorteos-twich V.1.0.0 .py"

      - name: Subir el archivo
        uses: actions/upload-artifact@v4
        with:
          name: Programa_Linux
          path: dist/Sorteo_Linux
