name: Compilar
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar PyInstaller
        run: pip install pyinstaller

      - name: Crear Exe
        # Este comando busca automaticamente cualquier archivo .py y lo compila
        run: |
          $pyFile = Get-ChildItem -Filter *.py | Select-Object -First 1 -ExpandProperty Name
          pyinstaller --onefile --windowed --name "Sorteo_Final" $pyFile

      - name: Subir Archivo
        uses: actions/upload-artifact@v4
        with:
          name: MiProgramaWindows
          path: dist/*.exe
