name: Compilar Sorteo Especial
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4
    
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar PyInstaller
        run: pip install pyinstaller
        
      - name: Crear el .exe
        # Aqui usamos comillas para que los espacios y puntos no den error
        run: pyinstaller --onefile --windowed --name "Sorteos-twich_TrikiVals_V.1.0.1" "Sorteos-twich TrikiVals_ V.1.0.1.py"

      - name: Subir el .exe final
        uses: actions/upload-artifact@v4
        with:
          name: Sorteo_Twich_TrikiVals
          path: dist/*.exe
